In [1]:
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

아무 문장이나 입력하세요 : 20210864
20210864


In [2]:
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]

In [3]:
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [4]:
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [5]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [6]:
arVal[1][2]

3.14

In [7]:
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [8]:
arVal[0][2]

't'

In [9]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [10]:
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [11]:
arData.sum()

15.44

In [12]:
arVal.sum()

AttributeError: 'list' object has no attribute 'sum'

In [13]:
print(type(arVal))
print(type(arData))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
arData.std()

1.4717934637713266

In [15]:
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [16]:
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [17]:
arData ** 2

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [18]:
np.sqrt(arData)

array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [19]:
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [20]:
arVal.sum(axis=0)

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [21]:
arVal.sum(axis=1)

array([15.44  , 58.5096])

In [22]:
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [24]:
import pandas as pd

pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [25]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [26]:
pandas_series[0]

30

In [27]:
pandas_series[0][1]

IndexError: invalid index to scalar variable.

In [28]:
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [29]:
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [30]:
df.columns

Index(['score'], dtype='object')

In [31]:
df.loc['국어']

score    30
Name: 국어, dtype: int64

In [32]:
df.sum()

score    60
dtype: int64

In [33]:
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [34]:
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [35]:
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [36]:
del df['score']

In [37]:
df['score2'] = (90, 90, 90, 100)

ValueError: Length of values (4) does not match length of index (3)

In [38]:
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score2
국어      90
영어      90
수학      90

In [39]:
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])

df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [40]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [41]:
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']

df

A         B         C         D         E
0  0.715103 -0.200690 -1.452059  0.800365  1.172998
1 -0.875125 -2.713289  1.070561 -1.777051 -0.644797
2  0.447581 -0.137668 -0.089898  0.349478 -0.277082
3  1.312635 -0.699744  1.769231 -0.397434 -1.653598
4 -0.912442  1.512456 -0.044369 -0.262491 -0.021611

In [42]:
df.max()

A    1.312635
B    1.512456
C    1.769231
D    0.800365
E    1.172998
dtype: float64

In [43]:
df.min()

A   -0.912442
B   -2.713289
C   -1.452059
D   -1.777051
E   -1.653598
dtype: float64

In [44]:
df.mean()

A    0.137550
B   -0.447787
C    0.250693
D   -0.257427
E   -0.284818
dtype: float64

In [45]:
df.std()

A    0.992283
B    1.516226
C    1.232941
D    0.976748
E    1.024415
dtype: float64

In [46]:
df.cumsum()

A         B         C         D         E
0  0.715103 -0.200690 -1.452059  0.800365  1.172998
1 -0.160022 -2.913980 -0.381498 -0.976686  0.528201
2  0.287559 -3.051647 -0.471397 -0.627208  0.251119
3  1.600193 -3.751391  1.297834 -1.024642 -1.402479
4  0.687751 -2.238935  1.253465 -1.287133 -1.424090

In [47]:
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.137550 -0.447787  0.250693 -0.257427 -0.284818
std    0.992283  1.516226  1.232941  0.976748  1.024415
min   -0.912442 -2.713289 -1.452059 -1.777051 -1.653598
25%   -0.875125 -0.699744 -0.089898 -0.397434 -0.644797
50%    0.447581 -0.200690 -0.044369 -0.262491 -0.277082
75%    0.715103 -0.137668  1.070561  0.349478 -0.021611
max    1.312635  1.512456  1.769231  0.800365  1.172998

In [48]:
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0  0.715103 -0.200690 -1.452059  0.800365  1.172998        X
1 -0.875125 -2.713289  1.070561 -1.777051 -0.644797        Y
2  0.447581 -0.137668 -0.089898  0.349478 -0.277082        X
3  1.312635 -0.699744  1.769231 -0.397434 -1.653598        Y
4 -0.912442  1.512456 -0.044369 -0.262491 -0.021611        Z

In [49]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X         0.581342 -0.169179 -0.770979  0.574922  0.447958
Y         0.218755 -1.706517  1.419896 -1.087243 -1.149197
Z        -0.912442  1.512456 -0.044369 -0.262491 -0.021611